---
title: "Coding test_Argus"
output: html_notebook
---


```{r}
library(gamlss)
library(gamlss.add)
library(gamlss.dist)
library(DT)
library(roll)
library(dplyr)
library(stats)
library(tseries)
library(ggpubr)
library(psych)
library(magrittr)
```


```{r}
# import data
Mydata <- function(rawdata) {
  oil_data <- rawdata 
  return(oil_data)
}

oil_data <- Mydata(gamlss.data::oil)

summary(oil_data)
```


```{r}
paste0("Oil dataset has ", dim(oil_data)[1], " observations and  ", dim(oil_data)[2], " variables. ")
```


```{r}
Mypipeline1 <- function(rawdata1) {

df <- as.data.frame(rawdata1)

oil_data2 <- rawdata1
oil_data2 <- as.matrix(oil_data2)

# rtolling standard deviation with window = 5
roll_sdDev <- roll::roll_sd(oil_data2, 5)

df$roll_sdDev <- roll_sdDev

# Rolling mean with window = 5
roll_mean <- roll::roll_mean(oil_data2, 5)
df$roll_mean <- roll_mean

# Lagging with order = 2
df$lag1 <- dplyr::lag(rawdata1,2)

# Leading with order = 2
df$lead <- dplyr::lead(rawdata1,2)

Diff <- rawdata1 %>% diff()
Diff[1000] <- NA
df$diff <- Diff

return(df)
}

oil_trans <- Mypipeline1(oil_data$OILPRICE)

head(oil_trans, n =20)

```


```{r}
Mypipeline2 <- function(rawdata2){
  
  df1 <- as.data.frame(rawdata2)
  df1$Ratio <- df1[,1]/df1[,2]
  df1$Product <- df1[,1] * df1[,2]
  
  return(df1)
  
}

df1 <- Mypipeline2(oil_trans[, c("roll_sdDev", "roll_mean")])

head(df1, n = 20)
```


```{r}
Mypipeline3 <- function(rawdata3){
  
  df2 <- as.data.frame(rawdata3)
  dif <- (df2$OILPRICE - df2$respLAG)
  df2$difference <- dif
  dif <- as.matrix(dif)
  roll_std <- roll::roll_sd(dif, 5)
  
  df2$comp_trans <- roll_std
  
  return(df2)
  
}

df2 <- Mypipeline3(data_oil[,c("OILPRICE", "respLAG")])

head(df2, n = 20)
 
```


```{r}
drivers <- cbind(oil_trans, df1, df2)
drivers <- 
  drivers[, c("rawdata1", "roll_sdDev", "roll_mean",
                       "lag1", "lead", "diff", "Ratio", "Product",
                       "comp_trans")]

head(drivers, n = 20)
```


```{r}
# check normality
normality_check <- function(input) {

  print(ggdensity(input, 
          main = "Rolling Standard deviation",
          xlab = ""))
  
  shapiro.test(input)
  
}

normality_check(drivers$roll_sdDev)
```


```{r}
# check stationarity
stationarity_chek <- function(input) {
  input[is.na(input)] <- 0
  tseries::adf.test(input)
}
stationarity_chek(drivers$roll_mean)
```
```{r}
# check correlation
correlation_check <- function(input){

  input[is.na(input)] <- 0
  return(psych::corPlot(input, cex = 0.5))
}

correlation_check(drivers)
```
```{r}
# I have used following links for the references of this test.
#https://rdrr.io/cran/gamlss.data/man/oil.html
#https://www.kaggle.com/gabrieloliveirasan/gamlss-in-r-oil-price-prediction
#http://www.gamlss.com/wp-content/uploads/2013/01/gamlss-manual.pdf
```

